apiVersion: v1
kind: Namespace
metadata:
  name: postech

---
apiVersion: v1
kind: Secret
metadata:
  name: autenticacao-secret
  namespace: postech
data:
  COGNITO_CLIENT_ID: #{COGNITO_CLIENT_ID}#
  DATABASE_URL: #{DATABASE_URL}#
  AWS_ACCESS_KEY_ID_B64: #{AWS_ACCESS_KEY_ID_B64}#
  AWS_SECRET_ACCESS_KEY_B64: #{AWS_SECRET_ACCESS_KEY_B64}#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autenticacao-config-map
  namespace: postech
data:
  AWS_REGION: "us-east-1"
  COGNITO_URL: "https://cognito-idp.us-east-1.amazonaws.com/"
  COGNITO_HEADER_SIGNUP: "AWSCognitoIdentityProviderService.SignUp"
  GOGNITO_HEADER_SIGNIN: "AWSCognitoIdentityProviderService.InitiateAuth"
  COGNITO_HEADER_GETUSER: "AWSCognitoIdentityProviderService.GetUser"
  COGNITO_HEADER_DELETEUSER: "AWSCognitoIdentityProviderService.DeleteUser"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autenticacao-deployment
  namespace: postech
  labels:
    app: autenticacao-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: autenticacao-deployment
    spec:
      containers:
        - name: autenticacao-image
          image: #{AUTENTICACAO_IMAGE}#
          ports:
            - containerPort: 3332
          envFrom:
            - secretRef:
                name: "autenticacao-secret"
            - configMapRef:
                name: "autenticacao-config-map"
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
  selector:
    matchLabels:
      app: autenticacao-deployment

---
apiVersion: v1
kind: Service
metadata:
  name: autenticacao-service
  namespace: postech
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: test
spec:
  ports:
    - port: 80
      targetPort: 3332
      protocol: TCP
  type: LoadBalancer
  selector:
    app: autenticacao-deployment

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autenticacao-hpa
  namespace: postech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autenticacao-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
