version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3332:3332
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/consulta
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autenticacao
    networks:
      - app-network

networks:
  app-network:
    driver: bridge